name:                hsudoku
version:             0.1.0.0
github:              "tomasaschan/hsudoku"
license:             BSD-3-Clause
author:              "Tomas Aschan"
maintainer:          "1550920+tomasaschan@users.noreply.github.com"
copyright:           "Tomas Aschan"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            util

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tomasaschan/hsudoku#readme>

dependencies:
- base >= 4.7 && < 5

- containers
- dequeue
- extra
- pretty
- text

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
# - -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hsudoku-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hsudoku

tests:
  hsudoku-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - hsudoku
    - hspec
    - hspec-discover
    - QuickCheck

default-extensions:
- OverloadedStrings
